### ISSUE TITLE
sentence boundary edit

### ISSUE THREAD

**Issue by kmcdono2** [thawsitt/philologic_webapp#14]
From Clovis-

Sure, the parser is here:
https://github.com/ARTFL-Project/PhiloLogic4/blob/master/python/philologic/NewParser.py
The load config file (which you pass as a command-line argument to the philoload4 command) is here:
https://github.com/ARTFL-Project/PhiloLogic4/blob/master/extras/load_config.py
You'll see line 230, you can define your own sentence boundaries.

Goal - edit sentence boundaries for Corpus Synodalium to be section <div>

**Comment by thawsitt** [comment]
- Look into replacing sentence boundaries with `<div>` sections.
