### ISSUE TITLE
Migrating content to Stanford servers

### ISSUE THREAD

**Issue by thawsitt** [thawsitt/philologic_webapp#5]
1. This is a project for the future. The current VPS server that I am using is very convenient and I'm satisfied with it.

2. I am currently using VPS (virtual private server) Hosting Service from [Namecheap](https://www.namecheap.com/hosting/vps.aspx). It is a funny name, but they provide reliable service and I also use it to host my personal website.

3. The website is now viewable at [http://rdorin.website/philologic/xmltest2/](http://rdorin.website/philologic/xmltest2/). I can change `xmltest2` to any other name you want in the production version. However, I can't change the values before it.

4.  If you don't like it, we can use a URL-shortening service such that `http://bit.do/philologic`, for example, will redirect to our web app url.

5.  However, we might need to move our website to Stanford's servers at some point. I have been looking at options from Stanford and it seems that a [virtual server](https://uit.stanford.edu/service/virtualserver) is the closest option to what we are currently using. 

6. I tried using Stanford's `cgi-bin` and it does not work so far. I think it will be limited even if it does.

7. @kmcdono2 Is there anyone who can point us in the right direction towards hosting an Apache server at Stanford? (PhiloLogic uses Apache server)

8. I will also try to ask Clovis and update this with more information later. Thanks!

**Comment by kmcdono2** [comment]
I am in the process of getting access to a VM through Digital Library Systems and Services. Will find out if this is Apache.

Good to know re: cgi-bin. That's a shame, but I will also investigate this further.

**Comment by kmcdono2** [comment]
@thawsitt These seem to be the specs for a Rails VM. Not sure if this is applicable to all DLSS VMs, but will know more soon.

apache
passenger gem
bundler gem
ruby version installed via RVM
an application user account
home defaults to /opt/app
folder structure for Capistrano deploys
defaults to /app_user_home/app_username/app_name
application logs symlinked to /var
mysql (optional)
gets a /var/log/mysql partition
database.yml file for the app
logrotate for services
port 80 and 443 open to Stanford nets

**Comment by kmcdono2** [comment]
VM
SSD drive + speed preferably (performance)
