### ISSUE TITLE
Exclude metadata in search results

### ISSUE THREAD

**Issue by kmcdono2** [thawsitt/philologic_webapp#7]
@thawsitt Metadata content is included in search results (from main search box, not from search options). This is skewing results by quite a lot some times (e.g. when you search for diocese/province/other words that appear consistently in the metadata).

**Comment by kmcdono2** [comment]
Ref: https://github.com/thawsitt/philologic_webapp/blob/master/code/philologic_config_files/custom_load_config.py#L185

Define a list of tags that you do not want parser to look at (for full text search).
[e.g. head tags]

**Comment by thawsitt** [comment]
- Completed in https://github.com/thawsitt/local-legislation/commit/d721e0f39334166407a7a2061e70319350ef21c6
